### ISSUE TITLE
Have markers in different colours

### ISSUE THREAD

**Issue by StefanBrand** [StefanBrand/fprsmap#15]
Make markers in different colours, following the Fairphone Color Guide:
![fairphone_color_guide](https://cloud.githubusercontent.com/assets/8948865/18416306/f47cb81a-7810-11e6-8115-acbbe312f2c7.png)

We should put them in their own directory.

**Comment by Roboe** [comment]
Great!

About the directories, I was planning to tidy files up once you merge #13, :)

**Comment by newluck77** [comment]
Okay! Please rename fprsmap01.js to simply fprsmap.js (fprsmap01.css 
respectively) in the process. It's a relict from my first tryouts with 
the map and has been bugging me ever since I uploaded it on Github... ^_^


Am 11.09.2016 um 11:55 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
I was planning to rename it to `main.js` or something similar... I'm going to draft it on #13

**Comment by newluck77** [comment]
Will make a PR to your cleaned up repo.
